const ADD_CONVERSION = "ADD_CONVERSION";
const SET_LOADING = "SET_LOADING";
const SET_CONVERSION_LIST = "SET_CONVERSION_LIST";


export {
    ADD_CONVERSION,
    SET_LOADING,
    SET_CONVERSION_LIST
}